"""initial migrations

Revision ID: 9b79bbf9e6cd
Revises: 
Create Date: 2026-02-03 11:13:31.047217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b79bbf9e6cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=False),
    sa.Column('otp_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('kyc_status', sa.Enum('unverified', 'pending', 'verified', 'rejected', name='kyc_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_users_kyc_status', ['kyc_status'], unique=False)
        batch_op.create_index('idx_users_phone_email', ['phone_number', 'email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=True),
    sa.Column('actor_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_logs_action_status', ['action', 'status'], unique=False)
        batch_op.create_index('idx_audit_logs_actor_action', ['actor_id', 'action'], unique=False)
        batch_op.create_index('idx_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_logs_request_id', ['request_id'], unique=False)
        batch_op.create_index('idx_audit_logs_resource', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)

    op.create_table('kyc_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('national_id', 'passport', 'driver_license', 'alien_card', name='document_type_enum'), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('document_front_url', sa.String(length=500), nullable=True),
    sa.Column('document_back_url', sa.String(length=500), nullable=True),
    sa.Column('selfie_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('unverified', 'pending', 'verified', 'rejected', name='kyc_status_enum'), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kyc_verifications', schema=None) as batch_op:
        batch_op.create_index('idx_kyc_document_number', ['document_number'], unique=False)
        batch_op.create_index('idx_kyc_status_submitted', ['status', 'submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_verifications_document_number'), ['document_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_verifications_user_id'), ['user_id'], unique=True)

    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('internal', 'mpesa', 'bank', 'card', name='payment_provider_enum'), nullable=False),
    sa.Column('account_reference', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'account_reference', name='unique_user_payment_method')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index('idx_payment_methods_account_ref', ['account_reference'], unique=False)
        batch_op.create_index('idx_payment_methods_is_default', ['is_default'], unique=False)
        batch_op.create_index('idx_payment_methods_user_provider', ['user_id', 'provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_methods_user_id'), ['user_id'], unique=False)

    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('locked_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('active', 'frozen', 'suspended', 'closed', name='wallet_status_enum'), nullable=False),
    sa.Column('daily_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_transaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('available_balance >= 0', name='check_non_negative_available'),
    sa.CheckConstraint('balance = available_balance + locked_balance', name='check_balance_consistency'),
    sa.CheckConstraint('balance >= 0', name='check_non_negative_balance'),
    sa.CheckConstraint('locked_balance >= 0', name='check_non_negative_locked'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index('idx_wallets_balance', ['balance'], unique=False)
        batch_op.create_index('idx_wallets_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_wallets_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallets_user_id'), ['user_id'], unique=True)

    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_wallet_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('total_transfers', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_transfer_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'beneficiary_wallet_id', name='unique_user_beneficiary')
    )
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.create_index('idx_beneficiaries_last_transfer', ['last_transfer_at'], unique=False)
        batch_op.create_index('idx_beneficiaries_user_category', ['user_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_beneficiaries_beneficiary_wallet_id'), ['beneficiary_wallet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_beneficiaries_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_wallet_id', sa.Integer(), nullable=True),
    sa.Column('receiver_wallet_id', sa.Integer(), nullable=True),
    sa.Column('external_sender', sa.String(length=100), nullable=True),
    sa.Column('external_receiver', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_type', sa.Enum('transfer', 'deposit', 'withdrawal', 'fee', name='transaction_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'reversed', name='transaction_status_enum'), nullable=False),
    sa.Column('provider', sa.Enum('internal', 'mpesa', 'bank', 'card', name='payment_provider_enum'), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_positive_amount'),
    sa.CheckConstraint('fee >= 0', name='check_non_negative_fee'),
    sa.CheckConstraint('net_amount = amount - fee', name='check_net_amount_calculation'),
    sa.CheckConstraint('net_amount > 0', name='check_positive_net_amount'),
    sa.ForeignKeyConstraint(['receiver_wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transactions_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_transactions_idempotency', ['idempotency_key'], unique=False)
        batch_op.create_index('idx_transactions_provider_ext', ['provider', 'external_reference'], unique=False)
        batch_op.create_index('idx_transactions_sender_receiver', ['sender_wallet_id', 'receiver_wallet_id'], unique=False)
        batch_op.create_index('idx_transactions_status_type', ['status', 'transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_external_reference'), ['external_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_receiver_wallet_id'), ['receiver_wallet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_sender_wallet_id'), ['sender_wallet_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_type IN ('debit', 'credit')", name='check_entry_type'),
    sa.CheckConstraint('balance_after = balance_before + amount', name='check_balance_calculation'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index('idx_ledger_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_ledger_entry_type', ['entry_type'], unique=False)
        batch_op.create_index('idx_ledger_wallet_transaction', ['wallet_id', 'transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_wallet_id'), ['wallet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_transaction_id'))
        batch_op.drop_index('idx_ledger_wallet_transaction')
        batch_op.drop_index('idx_ledger_entry_type')
        batch_op.drop_index('idx_ledger_created_at')

    op.drop_table('ledger_entries')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_sender_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_receiver_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_external_reference'))
        batch_op.drop_index('idx_transactions_status_type')
        batch_op.drop_index('idx_transactions_sender_receiver')
        batch_op.drop_index('idx_transactions_provider_ext')
        batch_op.drop_index('idx_transactions_idempotency')
        batch_op.drop_index('idx_transactions_created_at')

    op.drop_table('transactions')
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beneficiaries_user_id'))
        batch_op.drop_index(batch_op.f('ix_beneficiaries_beneficiary_wallet_id'))
        batch_op.drop_index('idx_beneficiaries_user_category')
        batch_op.drop_index('idx_beneficiaries_last_transfer')

    op.drop_table('beneficiaries')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_user_id'))
        batch_op.drop_index('idx_wallets_user_status')
        batch_op.drop_index('idx_wallets_created_at')
        batch_op.drop_index('idx_wallets_balance')

    op.drop_table('wallets')
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_user_id'))
        batch_op.drop_index('idx_payment_methods_user_provider')
        batch_op.drop_index('idx_payment_methods_is_default')
        batch_op.drop_index('idx_payment_methods_account_ref')

    op.drop_table('payment_methods')
    with op.batch_alter_table('kyc_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_verifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_kyc_verifications_document_number'))
        batch_op.drop_index('idx_kyc_status_submitted')
        batch_op.drop_index('idx_kyc_document_number')

    op.drop_table('kyc_verifications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('idx_audit_logs_resource')
        batch_op.drop_index('idx_audit_logs_request_id')
        batch_op.drop_index('idx_audit_logs_created_at')
        batch_op.drop_index('idx_audit_logs_actor_action')
        batch_op.drop_index('idx_audit_logs_action_status')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_public_id'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_users_phone_email')
        batch_op.drop_index('idx_users_kyc_status')
        batch_op.drop_index('idx_users_created_at')

    op.drop_table('users')
    # ### end Alembic commands ###
