"""initial migration

Revision ID: a2ab9fbfc888
Revises: 
Create Date: 2026-02-06 11:12:20.873893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2ab9fbfc888'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('trading_name', sa.String(length=200), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('country_of_incorporation', sa.String(length=2), nullable=False),
    sa.Column('date_of_incorporation', sa.Date(), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('mailing_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('primary_email', sa.String(length=120), nullable=False),
    sa.Column('primary_phone', sa.String(length=20), nullable=False),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('kyc_status', sa.String(length=20), nullable=False),
    sa.Column('kyc_level', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('compliance_notes', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.String(length=20), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('idx_accounts_country_type', ['country_of_incorporation', 'account_type'], unique=False)
        batch_op.create_index('idx_accounts_kyc_status', ['kyc_status', 'kyc_level'], unique=False)
        batch_op.create_index('idx_accounts_retention', ['retention_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_primary_email'), ['primary_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_primary_phone'), ['primary_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_registration_number'), ['registration_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_tax_id'), ['tax_id'], unique=False)

    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'target_currency', name='unique_currency_pair')
    )
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.create_index('idx_exchange_rate_currency', ['base_currency', 'target_currency'], unique=False)
        batch_op.create_index('idx_exchange_rate_updated', ['last_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_rates_base_currency'), ['base_currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_rates_target_currency'), ['target_currency'], unique=False)

    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applies_to', sa.JSON(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('calculation_type', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('source_countries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('destination_countries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.create_index('idx_fees_countries', ['source_countries', 'destination_countries'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_fees_effective', ['effective_from', 'effective_to'], unique=False)
        batch_op.create_index('idx_fees_type_active', ['fee_type', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_fees_fee_type'), ['fee_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('phone_country_code', sa.String(length=5), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('preferred_currency', sa.String(length=3), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('nationality', sa.String(length=2), nullable=True),
    sa.Column('residency_country', sa.String(length=2), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=False),
    sa.Column('otp_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('kyc_status', sa.Enum('unverified', 'pending', 'verified', 'rejected', name='kyc_status_enum'), nullable=False),
    sa.Column('kyc_level', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_ip_address', sa.String(length=45), nullable=True),
    sa.Column('last_device_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_location_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_kyc_review', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_country_region', ['country_code', 'region'], unique=False)
        batch_op.create_index('idx_users_kyc_level', ['kyc_status', 'kyc_level'], unique=False)
        batch_op.create_index('idx_users_language_currency', ['language', 'preferred_currency'], unique=False)
        batch_op.create_index('idx_users_phone_full', ['phone_country_code', 'phone_number'], unique=False)
        batch_op.create_index('idx_users_risk_score', ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=True),
    sa.Column('actor_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_logs_action_status', ['action', 'status'], unique=False)
        batch_op.create_index('idx_audit_logs_actor_action', ['actor_id', 'action'], unique=False)
        batch_op.create_index('idx_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_logs_request_id', ['request_id'], unique=False)
        batch_op.create_index('idx_audit_logs_resource', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)

    op.create_table('funding_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.Enum('internal', 'mpesa', 'bank', 'card', name='payment_provider_enum'), nullable=True),
    sa.Column('masked_identifier', sa.String(length=100), nullable=False),
    sa.Column('full_identifier', sa.String(length=200), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('institution_name', sa.String(length=100), nullable=True),
    sa.Column('institution_code', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=30), nullable=True),
    sa.Column('daily_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monthly_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_deposits', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'masked_identifier', name='unique_user_funding_source')
    )
    with op.batch_alter_table('funding_sources', schema=None) as batch_op:
        batch_op.create_index('idx_funding_sources_country', ['country'], unique=False)
        batch_op.create_index('idx_funding_sources_user_type', ['user_id', 'source_type'], unique=False)
        batch_op.create_index('idx_funding_sources_verified', ['is_verified', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_sources_masked_identifier'), ['masked_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_sources_user_id'), ['user_id'], unique=False)

    op.create_table('kyc_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('national_id', 'passport', 'driver_license', 'alien_card', name='document_type_enum'), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('document_front_url', sa.String(length=500), nullable=True),
    sa.Column('document_back_url', sa.String(length=500), nullable=True),
    sa.Column('selfie_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('unverified', 'pending', 'verified', 'rejected', name='kyc_status_enum'), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kyc_verifications', schema=None) as batch_op:
        batch_op.create_index('idx_kyc_document_number', ['document_number'], unique=False)
        batch_op.create_index('idx_kyc_status_submitted', ['status', 'submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_verifications_document_number'), ['document_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_verifications_user_id'), ['user_id'], unique=True)

    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('internal', 'mpesa', 'bank', 'card', name='payment_provider_enum'), nullable=False),
    sa.Column('account_reference', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'account_reference', name='unique_user_payment_method')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index('idx_payment_methods_account_ref', ['account_reference'], unique=False)
        batch_op.create_index('idx_payment_methods_is_default', ['is_default'], unique=False)
        batch_op.create_index('idx_payment_methods_user_provider', ['user_id', 'provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_methods_user_id'), ['user_id'], unique=False)

    op.create_table('payout_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('destination_type', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.Enum('internal', 'mpesa', 'bank', 'card', name='payment_provider_enum'), nullable=True),
    sa.Column('masked_identifier', sa.String(length=100), nullable=False),
    sa.Column('full_identifier', sa.String(length=200), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('institution_name', sa.String(length=100), nullable=True),
    sa.Column('institution_code', sa.String(length=20), nullable=True),
    sa.Column('branch_code', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=30), nullable=True),
    sa.Column('daily_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monthly_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_payouts', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'masked_identifier', name='unique_user_payout_destination')
    )
    with op.batch_alter_table('payout_destinations', schema=None) as batch_op:
        batch_op.create_index('idx_payout_destinations_country', ['country'], unique=False)
        batch_op.create_index('idx_payout_destinations_user_type', ['user_id', 'destination_type'], unique=False)
        batch_op.create_index('idx_payout_destinations_verified', ['is_verified', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_destinations_masked_identifier'), ['masked_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_destinations_user_id'), ['user_id'], unique=False)

    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', name='unique_user_account')
    )
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.create_index('idx_user_accounts_primary', ['user_id', 'is_primary'], unique=False)
        batch_op.create_index('idx_user_accounts_role', ['account_id', 'role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_accounts_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('locked_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency_balances', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_currency', sa.String(length=3), nullable=False),
    sa.Column('supported_currencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('active', 'frozen', 'suspended', 'closed', name='wallet_status_enum'), nullable=False),
    sa.Column('daily_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cross_border_daily_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cross_border_monthly_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('daily_usage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_usage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cross_border_daily_usage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cross_border_monthly_usage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('daily_usage_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_usage_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cross_border_daily_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cross_border_monthly_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_screened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('ledger_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_transaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('available_balance >= 0', name='check_non_negative_available'),
    sa.CheckConstraint('balance >= 0', name='check_non_negative_balance'),
    sa.CheckConstraint('locked_balance >= 0', name='check_non_negative_locked'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index('idx_wallets_currency_balances', ['currency_balances'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_wallets_daily_reset', ['daily_usage_reset_at'], unique=False)
        batch_op.create_index('idx_wallets_monthly_reset', ['monthly_usage_reset_at'], unique=False)
        batch_op.create_index('idx_wallets_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallets_user_id'), ['user_id'], unique=True)

    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_wallet_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('total_transfers', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_transfer_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'beneficiary_wallet_id', name='unique_user_beneficiary')
    )
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.create_index('idx_beneficiaries_last_transfer', ['last_transfer_at'], unique=False)
        batch_op.create_index('idx_beneficiaries_user_category', ['user_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_beneficiaries_beneficiary_wallet_id'), ['beneficiary_wallet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_beneficiaries_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_wallet_id', sa.Integer(), nullable=True),
    sa.Column('receiver_wallet_id', sa.Integer(), nullable=True),
    sa.Column('external_sender', sa.String(length=100), nullable=True),
    sa.Column('external_receiver', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source_currency', sa.String(length=3), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('fx_provider', sa.String(length=50), nullable=True),
    sa.Column('fx_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_country', sa.String(length=2), nullable=True),
    sa.Column('destination_country', sa.String(length=2), nullable=True),
    sa.Column('is_cross_border', sa.Boolean(), nullable=False),
    sa.Column('transaction_type', sa.Enum('transfer', 'deposit', 'withdrawal', 'fee', name='transaction_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'reversed', name='transaction_status_enum'), nullable=False),
    sa.Column('provider', sa.Enum('internal', 'mpesa', 'bank', 'card', name='payment_provider_enum'), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('debit_status', sa.String(length=20), nullable=True),
    sa.Column('credit_status', sa.String(length=20), nullable=True),
    sa.Column('settlement_status', sa.String(length=20), nullable=True),
    sa.Column('settlement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_reference', sa.String(length=100), nullable=True),
    sa.Column('failure_domain', sa.String(length=20), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(length=50), nullable=True),
    sa.Column('reporting_category', sa.String(length=50), nullable=True),
    sa.Column('is_reportable', sa.Boolean(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('original_transaction_id', sa.Integer(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('is_reversal', sa.Boolean(), nullable=False),
    sa.Column('is_refund', sa.Boolean(), nullable=False),
    sa.Column('funding_source_id', sa.Integer(), nullable=True),
    sa.Column('payout_destination_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_positive_amount'),
    sa.CheckConstraint('fee >= 0', name='check_non_negative_fee'),
    sa.CheckConstraint('net_amount = amount - fee', name='check_net_amount_calculation'),
    sa.CheckConstraint('net_amount > 0', name='check_positive_net_amount'),
    sa.ForeignKeyConstraint(['funding_source_id'], ['funding_sources.id'], ),
    sa.ForeignKeyConstraint(['original_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['payout_destination_id'], ['payout_destinations.id'], ),
    sa.ForeignKeyConstraint(['receiver_wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transactions_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_transactions_cross_border', ['is_cross_border'], unique=False)
        batch_op.create_index('idx_transactions_idempotency', ['idempotency_key'], unique=False)
        batch_op.create_index('idx_transactions_original', ['original_transaction_id'], unique=False)
        batch_op.create_index('idx_transactions_provider_ext', ['provider', 'external_reference'], unique=False)
        batch_op.create_index('idx_transactions_sender_receiver', ['sender_wallet_id', 'receiver_wallet_id'], unique=False)
        batch_op.create_index('idx_transactions_sequence', ['sequence_number'], unique=False)
        batch_op.create_index('idx_transactions_settlement', ['settlement_status', 'settlement_date'], unique=False)
        batch_op.create_index('idx_transactions_source_dest', ['source_country', 'destination_country'], unique=False)
        batch_op.create_index('idx_transactions_status_type', ['status', 'transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_external_reference'), ['external_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_receiver_wallet_id'), ['receiver_wallet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_sender_wallet_id'), ['sender_wallet_id'], unique=False)

    op.create_table('holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('hold_type', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_release', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('resolution_action', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holds', schema=None) as batch_op:
        batch_op.create_index('idx_holds_created', ['created_at'], unique=False)
        batch_op.create_index('idx_holds_expiry', ['expires_at', 'status'], unique=False)
        batch_op.create_index('idx_holds_type_status', ['hold_type', 'status'], unique=False)
        batch_op.create_index('idx_holds_wallet_status', ['wallet_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_holds_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_holds_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holds_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('fx_provider', sa.String(length=50), nullable=True),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('entry_subtype', sa.String(length=20), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_type IN ('debit', 'credit')", name='check_entry_type'),
    sa.CheckConstraint('balance_after = balance_before + amount', name='check_balance_calculation'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index('idx_ledger_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_ledger_currency', ['currency'], unique=False)
        batch_op.create_index('idx_ledger_entry_type', ['entry_type'], unique=False)
        batch_op.create_index('idx_ledger_sequence', ['wallet_id', 'sequence_number'], unique=True)
        batch_op.create_index('idx_ledger_wallet_date', ['wallet_id', 'created_at'], unique=False)
        batch_op.create_index('idx_ledger_wallet_transaction', ['wallet_id', 'transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_wallet_id'), ['wallet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_currency'))
        batch_op.drop_index('idx_ledger_wallet_transaction')
        batch_op.drop_index('idx_ledger_wallet_date')
        batch_op.drop_index('idx_ledger_sequence')
        batch_op.drop_index('idx_ledger_entry_type')
        batch_op.drop_index('idx_ledger_currency')
        batch_op.drop_index('idx_ledger_created_at')

    op.drop_table('ledger_entries')
    with op.batch_alter_table('holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holds_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_holds_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_holds_public_id'))
        batch_op.drop_index('idx_holds_wallet_status')
        batch_op.drop_index('idx_holds_type_status')
        batch_op.drop_index('idx_holds_expiry')
        batch_op.drop_index('idx_holds_created')

    op.drop_table('holds')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_sender_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_receiver_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_external_reference'))
        batch_op.drop_index('idx_transactions_status_type')
        batch_op.drop_index('idx_transactions_source_dest')
        batch_op.drop_index('idx_transactions_settlement')
        batch_op.drop_index('idx_transactions_sequence')
        batch_op.drop_index('idx_transactions_sender_receiver')
        batch_op.drop_index('idx_transactions_provider_ext')
        batch_op.drop_index('idx_transactions_original')
        batch_op.drop_index('idx_transactions_idempotency')
        batch_op.drop_index('idx_transactions_cross_border')
        batch_op.drop_index('idx_transactions_created_at')

    op.drop_table('transactions')
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beneficiaries_user_id'))
        batch_op.drop_index(batch_op.f('ix_beneficiaries_beneficiary_wallet_id'))
        batch_op.drop_index('idx_beneficiaries_user_category')
        batch_op.drop_index('idx_beneficiaries_last_transfer')

    op.drop_table('beneficiaries')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_user_id'))
        batch_op.drop_index('idx_wallets_user_status')
        batch_op.drop_index('idx_wallets_monthly_reset')
        batch_op.drop_index('idx_wallets_daily_reset')
        batch_op.drop_index('idx_wallets_currency_balances', postgresql_using='gin')

    op.drop_table('wallets')
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_accounts_account_id'))
        batch_op.drop_index('idx_user_accounts_role')
        batch_op.drop_index('idx_user_accounts_primary')

    op.drop_table('user_accounts')
    with op.batch_alter_table('payout_destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_destinations_user_id'))
        batch_op.drop_index(batch_op.f('ix_payout_destinations_masked_identifier'))
        batch_op.drop_index('idx_payout_destinations_verified')
        batch_op.drop_index('idx_payout_destinations_user_type')
        batch_op.drop_index('idx_payout_destinations_country')

    op.drop_table('payout_destinations')
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_user_id'))
        batch_op.drop_index('idx_payment_methods_user_provider')
        batch_op.drop_index('idx_payment_methods_is_default')
        batch_op.drop_index('idx_payment_methods_account_ref')

    op.drop_table('payment_methods')
    with op.batch_alter_table('kyc_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_verifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_kyc_verifications_document_number'))
        batch_op.drop_index('idx_kyc_status_submitted')
        batch_op.drop_index('idx_kyc_document_number')

    op.drop_table('kyc_verifications')
    with op.batch_alter_table('funding_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funding_sources_user_id'))
        batch_op.drop_index(batch_op.f('ix_funding_sources_masked_identifier'))
        batch_op.drop_index('idx_funding_sources_verified')
        batch_op.drop_index('idx_funding_sources_user_type')
        batch_op.drop_index('idx_funding_sources_country')

    op.drop_table('funding_sources')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('idx_audit_logs_resource')
        batch_op.drop_index('idx_audit_logs_request_id')
        batch_op.drop_index('idx_audit_logs_created_at')
        batch_op.drop_index('idx_audit_logs_actor_action')
        batch_op.drop_index('idx_audit_logs_action_status')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_public_id'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_users_risk_score')
        batch_op.drop_index('idx_users_phone_full')
        batch_op.drop_index('idx_users_language_currency')
        batch_op.drop_index('idx_users_kyc_level')
        batch_op.drop_index('idx_users_country_region')

    op.drop_table('users')
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fees_fee_type'))
        batch_op.drop_index('idx_fees_type_active')
        batch_op.drop_index('idx_fees_effective')
        batch_op.drop_index('idx_fees_countries', postgresql_using='gin')

    op.drop_table('fees')
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rates_target_currency'))
        batch_op.drop_index(batch_op.f('ix_exchange_rates_base_currency'))
        batch_op.drop_index('idx_exchange_rate_updated')
        batch_op.drop_index('idx_exchange_rate_currency')

    op.drop_table('exchange_rates')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_tax_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_registration_number'))
        batch_op.drop_index(batch_op.f('ix_accounts_public_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_primary_phone'))
        batch_op.drop_index(batch_op.f('ix_accounts_primary_email'))
        batch_op.drop_index('idx_accounts_retention')
        batch_op.drop_index('idx_accounts_kyc_status')
        batch_op.drop_index('idx_accounts_country_type')

    op.drop_table('accounts')
    # ### end Alembic commands ###
