CREATE TYPE "TransactionStatus" AS ENUM (
  'pending',
  'processing',
  'completed',
  'failed',
  'reversed'
);

CREATE TYPE "TransactionType" AS ENUM (
  'transfer',
  'deposit',
  'withdrawal',
  'fee'
);

CREATE TYPE "KYCStatus" AS ENUM (
  'unverified',
  'pending',
  'verified',
  'rejected'
);

CREATE TYPE "WalletStatus" AS ENUM (
  'active',
  'frozen',
  'suspended',
  'closed'
);

CREATE TYPE "PaymentProvider" AS ENUM (
  'internal',
  'mpesa',
  'bank',
  'card'
);

CREATE TYPE "DocumentType" AS ENUM (
  'national_id',
  'passport',
  'driver_license',
  'alien_card'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE NOT NULL,
  "email" varchar(120) UNIQUE NOT NULL,
  "username" varchar(80) UNIQUE NOT NULL,
  "phone_number" varchar(20) UNIQUE NOT NULL,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "date_of_birth" date,
  "password_hash" varchar(255) NOT NULL,
  "two_factor_enabled" boolean NOT NULL DEFAULT false,
  "last_login_at" datetime,
  "is_admin" boolean NOT NULL DEFAULT false,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_verified" boolean NOT NULL DEFAULT false,
  "kyc_status" "KYCStatus" NOT NULL DEFAULT (unverified),
  "created_at" datetime NOT NULL,
  "updated_at" datetime
);

CREATE TABLE "wallets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "balance" decimal(12,2) NOT NULL DEFAULT 0,
  "available_balance" decimal(12,2) NOT NULL DEFAULT 0,
  "locked_balance" decimal(12,2) NOT NULL DEFAULT 0,
  "currency" varchar(3) NOT NULL DEFAULT 'KES',
  "status" "WalletStatus" NOT NULL DEFAULT (active),
  "daily_limit" decimal(12,2) NOT NULL DEFAULT 100000,
  "monthly_limit" decimal(12,2) NOT NULL DEFAULT 1000000,
  "created_at" datetime NOT NULL,
  "updated_at" datetime,
  "last_transaction_at" datetime
);

CREATE TABLE "kyc_verifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "document_type" "DocumentType",
  "document_number" varchar(50),
  "document_front_url" varchar(500),
  "document_back_url" varchar(500),
  "selfie_url" varchar(500),
  "status" "KYCStatus" NOT NULL DEFAULT (unverified),
  "verified_by" int,
  "rejection_reason" text,
  "submitted_at" datetime,
  "verified_at" datetime,
  "expires_at" datetime,
  "created_at" datetime NOT NULL,
  "updated_at" datetime
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_wallet_id" int,
  "receiver_wallet_id" int,
  "external_sender" varchar(100),
  "external_receiver" varchar(100),
  "amount" decimal(12,2) NOT NULL,
  "fee" decimal(12,2) NOT NULL DEFAULT 0,
  "net_amount" decimal(12,2) NOT NULL,
  "transaction_type" "TransactionType" NOT NULL,
  "status" "TransactionStatus" NOT NULL DEFAULT (pending),
  "provider" "PaymentProvider" NOT NULL DEFAULT (internal),
  "reference" varchar(100) UNIQUE NOT NULL,
  "external_reference" varchar(100),
  "idempotency_key" uuid UNIQUE NOT NULL,
  "description" text,
  "metadata" json,
  "created_at" datetime NOT NULL,
  "initiated_at" datetime,
  "processed_at" datetime,
  "completed_at" datetime,
  "reversed_at" datetime
);

CREATE TABLE "ledger_entries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "wallet_id" int NOT NULL,
  "transaction_id" int NOT NULL,
  "amount" decimal(12,2) NOT NULL,
  "balance_before" decimal(12,2) NOT NULL,
  "balance_after" decimal(12,2) NOT NULL,
  "entry_type" varchar(10) NOT NULL,
  "description" text,
  "created_at" datetime NOT NULL
);

CREATE TABLE "beneficiaries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "beneficiary_wallet_id" int NOT NULL,
  "nickname" varchar(50),
  "category" varchar(20),
  "total_transfers" int NOT NULL DEFAULT 0,
  "total_amount" decimal(12,2) NOT NULL DEFAULT 0,
  "last_transfer_at" datetime,
  "daily_limit" decimal(12,2),
  "is_trusted" boolean NOT NULL DEFAULT false,
  "created_at" datetime NOT NULL,
  "updated_at" datetime
);

CREATE TABLE "payment_methods" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "provider" "PaymentProvider" NOT NULL,
  "account_reference" varchar(50) NOT NULL,
  "account_name" varchar(100),
  "provider_metadata" json,
  "is_default" boolean NOT NULL DEFAULT false,
  "is_verified" boolean NOT NULL DEFAULT false,
  "is_active" boolean NOT NULL DEFAULT true,
  "verification_token" varchar(100),
  "verified_at" datetime,
  "created_at" datetime NOT NULL,
  "updated_at" datetime,
  "last_used_at" datetime
);

CREATE TABLE "audit_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "actor_id" int,
  "actor_type" varchar(20),
  "actor_ip" varchar(45),
  "user_agent" text,
  "action" varchar(100) NOT NULL,
  "resource_type" varchar(50) NOT NULL,
  "resource_id" int,
  "old_values" jsonb,
  "new_values" jsonb,
  "request_id" varchar(100),
  "endpoint" varchar(200),
  "http_method" varchar(10),
  "status" varchar(20) NOT NULL DEFAULT 'success',
  "error_message" text,
  "created_at" datetime NOT NULL
);

CREATE INDEX "idx_payment_methods_user_provider" ON "payment_methods" ("user_id", "provider");

CREATE INDEX "idx_payment_methods_account_ref" ON "payment_methods" ("account_reference");

CREATE INDEX "idx_payment_methods_is_default" ON "payment_methods" ("is_default");

CREATE UNIQUE INDEX "unique_user_payment_method" ON "payment_methods" ("user_id", "provider", "account_reference");

COMMENT ON COLUMN "ledger_entries"."entry_type" IS 'debit or credit';

ALTER TABLE "wallets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "kyc_verifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "kyc_verifications" ADD FOREIGN KEY ("verified_by") REFERENCES "users" ("id");

ALTER TABLE "beneficiaries" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "beneficiaries" ADD FOREIGN KEY ("beneficiary_wallet_id") REFERENCES "wallets" ("id");

ALTER TABLE "payment_methods" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "ledger_entries" ADD FOREIGN KEY ("wallet_id") REFERENCES "wallets" ("id");

ALTER TABLE "ledger_entries" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("sender_wallet_id") REFERENCES "wallets" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("receiver_wallet_id") REFERENCES "wallets" ("id");

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("actor_id") REFERENCES "users" ("id");
